steps:
  - uses: actions/checkout@v2.3.2
    name: Check out code

  - uses: mr-smithers-excellent/docker-build-push@v4
    name: Build & push Docker image
    with:
      image: repo/image
      tag: latest
      registry: registry-url.io
      dockerfile: Dockerfile.ci
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
